### ISSUE TITLE
DeploymentOptimization.apply fails due to error in kubernetes_asyncio library

### ISSUE THREAD

**Issue by linkous8** [opsani/servox#80]
I've reproduced the issue on master for thoroughness but the log ([master_output.txt](https://github.com/opsani/servox/files/5525750/master_output.txt)) isn't very useful due to https://github.com/opsani/servox/issues/79

See this log from my dev branch for more complete error information: [dev_branch_output.txt](https://github.com/opsani/servox/files/5525763/dev_branch_output.txt)

**Comment by linkous8** [comment]
Running `poetry lock` to update dependencies seems to have rectified the error kubernetes_asyncio was giving. However it now times out with no explicit error given: [new_lock_output.txt](https://github.com/opsani/servox/files/5526067/new_lock_output.txt)

```
2020-11-11 12:34:16.206 | INFO     | servo.connectors.kubernetes:apply:2278 | kubernetes[adjust] - Applying 3 Kubernetes adjustments: [web-main/main.cpu=0.5, web-main/main.mem=0.5, web-main/main.replicas=1]
2020-11-11 12:34:16.209 | INFO     | servo.connectors.kubernetes:apply:2285 | kubernetes[adjust] - adjusting web-main/main: web-main/main.cpu=0.5
2020-11-11 12:34:16.210 | INFO     | servo.connectors.kubernetes:apply:2285 | kubernetes[adjust] - adjusting web-main/main: web-main/main.mem=0.5
2020-11-11 12:34:16.211 | INFO     | servo.connectors.kubernetes:apply:2285 | kubernetes[adjust] - adjusting web-main/main: web-main/main.replicas=1
2020-11-11 12:34:16.211 | DEBUG    | servo.connectors.kubernetes:apply:2294 | kubernetes[adjust] - waiting for adjustments to take effect on 1 optimizations
2020-11-11 12:34:16.231 | INFO     | servo.connectors.kubernetes:apply:1865 | kubernetes[adjust] - Using label_selector=app=web,role=main, resource_version=2335
2020-11-11 12:39:16.311 | ERROR    | servo.connectors.kubernetes:apply:2316 | kubernetes[adjust] - timed out after 5m waiting for adjustments to apply
2020-11-11 12:39:16.312 | INFO     | servo.connectors.kubernetes:rollback:1761 | kubernetes[adjust] - adjustment failed: rolling back deployment... ()
2020-11-11 12:39:16.327 | ERROR    | servo.runner:main_loop:246 | servo - failed with unrecoverable error: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 11 Nov 2020 18:39:16 GMT', 'Content-Length': '174')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}


Traceback (most recent call last):
...
```

**Comment by blakewatters** [comment]
I suspect that you are just hitting the known rollback issue discussed on #81. You can switch the `on_failure` option in the config off of rollback until we sort it out.

Somewhere along the line, I screwed up the rollback implementation and it's been rattling around in the backlog because it doesn't affect the Opsani Dev deployments I have been focused on.

Closing this as I think #79 and #81 cover the real issues. Reopen if there's another piece to the puzzle we need to track separately.

**Comment by linkous8** [comment]
@blakewatters I think you're mistaken here, note the following line from the new_lock_output.txt:

`2020-11-11 12:39:16.311 | ERROR    | servo.connectors.kubernetes:apply:2316 | kubernetes[adjust] - timed out after 5m waiting for adjustments to apply`

Heres a stack trace that came from my dev branch with the tentative #79 fix. Note the rollback failure from #81 is secondary to the issue encountered wherein the logic of [this loop](https://github.com/opsani/servox/blob/b45820c564a1db956a691149bac87ecc84bf7a0d/servo/connectors/kubernetes.py#L1876) is running forever (until the [external timeout](https://github.com/opsani/servox/blob/b45820c564a1db956a691149bac87ecc84bf7a0d/servo/connectors/kubernetes.py#L2303) is hit)

```
2020-11-11 13:11:24.574 | INFO     | servo.connectors.kubernetes:apply:1865 | kubernetes[adjust] - Using label_selector=app=web,role=main, resource_version=1149
2020-11-11 13:16:24.643 | ERROR    | servo.connectors.kubernetes:apply:2316 | kubernetes[adjust] - timed out after 5m waiting for adjustments to apply
2020-11-11 13:16:24.644 | INFO     | servo.connectors.kubernetes:rollback:1761 | kubernetes[adjust] - adjustment failed: rolling back deployment... ()
2020-11-11 13:16:24.662 | ERROR    | servo.runner:main_loop:246 | servo - failed with unrecoverable error: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 11 Nov 2020 19:16:24 GMT', 'Content-Length': '174')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}


Traceback (most recent call last):

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 2298, in apply
    results = await asyncio.wait_for(
                    │       └ <function wait_for at 0x7f065bb53ca0>
                    └ <module 'asyncio' from '/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/__init__.py'>

  File "/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
          │          └ <class 'asyncio.exceptions.TimeoutError'>
          └ <module 'asyncio.exceptions' from '/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/exceptions.py'>

asyncio.exceptions.TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/bin/servo", line 11, in <module>
    load_entry_point('servox', 'console_scripts', 'servo')()
    └ <function load_entry_point at 0x7f065c9d0dc0>

  File "/home/linkous/code_review/servox/servo/entry_points.py", line 34, in run_cli
    cli()
    └ <servo.cli.ServoCLI object at 0x7f065c7b25b0>

  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           │           │      │       └ {}
           │           │      └ ()
           │           └ <servo.cli.ServoCLI object at 0x7f065c7b25b0>
           └ <function get_command at 0x7f065acaeb80>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f065acde670>
           └ <OrderedGroup servo>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <servo.cli.Context object at 0x7f06599b5610>
         │    └ <function MultiCommand.invoke at 0x7f065acdf430>
         └ <OrderedGroup servo>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <servo.cli.Context object at 0x7f065995b760>
           │               │       │       └ <function Command.invoke at 0x7f065acdf040>
           │               │       └ <Command run>
           │               └ <servo.cli.Context object at 0x7f065995b760>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f0659959670>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'check': False}
           │   │      │    │           └ <servo.cli.Context object at 0x7f065995b760>
           │   │      │    └ <function ServoCLI.add_ops_commands.<locals>.run at 0x7f0659945310>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7f065acde160>
           └ <servo.cli.Context object at 0x7f065995b760>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'check': False}
           │         └ ()
           └ <function ServoCLI.add_ops_commands.<locals>.run at 0x7f0659945310>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
           │          └ {'context': <servo.cli.Context object at 0x7f065995b760>, 'check': False}
           └ <function ServoCLI.add_ops_commands.<locals>.run at 0x7f06599b6670>

  File "/home/linkous/code_review/servox/servo/cli.py", line 1031, in run
    servo.runner.Runner(context.assembly).run()
    │     │      │      │       └ Assembly(config_file=PosixPath('/home/linkous/code_review/servox/servo.yaml'), optimizer=Optimizer(org_domain='dev.opsani.com...
    │     │      │      └ <servo.cli.Context object at 0x7f065995b760>
    │     │      └ <class 'servo.runner.Runner'>
    │     └ <module 'servo.runner' from '/home/linkous/code_review/servox/servo/runner.py'>
    └ <module 'servo' from '/home/linkous/code_review/servox/servo/__init__.py'>

  File "/home/linkous/code_review/servox/servo/runner.py", line 354, in run
    loop.run_forever()
    │    └ <method 'run_forever' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>

> File "/home/linkous/code_review/servox/servo/runner.py", line 240, in main_loop
    status = await self.exec_command()
                   │    └ <function Runner.exec_command at 0x7f065acc41f0>
                   └ <servo.runner.Runner object at 0x7f065990ceb0>

  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
                │       │       └ {}
                │       └ (<servo.runner.Runner object at 0x7f065990ceb0>,)
                └ <function Runner.exec_command at 0x7f065acbfaf0>

  File "/home/linkous/code_review/servox/servo/runner.py", line 205, in exec_command
    description = await self.adjust(adjustments, control)
                        │    │      │            └ Control(duration=Duration('0' 0:00:00), delay=Duration('0' 0:00:00), warmup=Duration('0' 0:00:00), settlement=None, load=None...
                        │    │      └ [Adjustment(component_name='web-main/main', setting_name='cpu', value='0.25'), Adjustment(component_name='web-main/main', set...
                        │    └ <function Runner.adjust at 0x7f065acbf9d0>
                        └ <servo.runner.Runner object at 0x7f065990ceb0>

  File "/home/linkous/code_review/servox/servo/runner.py", line 165, in adjust
    results = await self.servo.dispatch_event(servo.Events.ADJUST, adjustments)
                    │    │                    │     │      │       └ [Adjustment(component_name='web-main/main', setting_name='cpu', value='0.25'), Adjustment(component_name='web-main/main', set...
                    │    │                    │     │      └ <Events.ADJUST: 'adjust'>
                    │    │                    │     └ <enum 'Events'>
                    │    │                    └ <module 'servo' from '/home/linkous/code_review/servox/servo/__init__.py'>
                    │    └ <property object at 0x7f065acba450>
                    └ <servo.runner.Runner object at 0x7f065990ceb0>

  File "/home/linkous/code_review/servox/servo/events.py", line 780, in dispatch_event
    results = await group
                    └ <_GatheringFuture finished exception=ApiException()>

  File "/home/linkous/code_review/servox/servo/events.py", line 866, in run_event_handlers
    raise error

  File "/home/linkous/code_review/servox/servo/events.py", line 836, in run_event_handlers
    value = await asyncio.create_task(
                  │       └ <function create_task at 0x7f065bb53280>
                  └ <module 'asyncio' from '/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/__init__.py'>

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 2775, in adjust
    await state.apply(adjustments)
          │     │     └ [Adjustment(component_name='web-main/main', setting_name='cpu', value='0.25'), Adjustment(component_name='web-main/main', set...
          │     └ <function KubernetesOptimizations.apply at 0x7f0659aa1670>
          └ KubernetesOptimizations(config=KubernetesConfiguration(description='co-http web deployment', kubeconfig=None, context=None, n...

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 2320, in apply
    if await optimization.handle_error(error, self.config.on_failure):
             │            │                   │    │      └ <FailureMode.ROLLBACK: 'rollback'>
             │            │                   │    └ KubernetesConfiguration(description='co-http web deployment', kubeconfig=None, context=None, namespace='default', settlement=...
             │            │                   └ KubernetesOptimizations(config=KubernetesConfiguration(description='co-http web deployment', kubeconfig=None, context=None, n...
             │            └ <function BaseOptimization.handle_error at 0x7f0659a925e0>
             └ DeploymentOptimization(name='web-main/main', timeout=Duration('5m' 0:05:00), deployment_config=DeploymentConfiguration(descri...

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 1630, in handle_error
    await self.rollback(error)
          │    │        └ TimeoutError()
          │    └ <function DeploymentOptimization.rollback at 0x7f0659a92af0>
          └ DeploymentOptimization(name='web-main/main', timeout=Duration('5m' 0:05:00), deployment_config=DeploymentConfiguration(descri...

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 1762, in rollback
    await asyncio.wait_for(
          │       └ <function wait_for at 0x7f065bb53ca0>
          └ <module 'asyncio' from '/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/__init__.py'>

  File "/home/linkous/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Future' objects>
           └ <_GatheringFuture finished exception=ApiException()>

  File "/home/linkous/code_review/servox/servo/connectors/kubernetes.py", line 1177, in rollback
    self.obj = await api_client.create_namespaced_deployment_rollback(
    │    │           │          └ <function ExtensionsV1beta1Api.create_namespaced_deployment_rollback at 0x7f0659c948b0>
    │    │           └ <kubernetes_asyncio.client.api.extensions_v1beta1_api.ExtensionsV1beta1Api object at 0x7f065763aeb0>
    │    └ {'api_version': 'apps/v1',
    │       'kind': 'Deployment',
    │       'metadata': {'annotations': {'deployment.kubernetes.io/revision': '5',
    │         ...
    └ {'api_version': 'apps/v1',
       'kind': 'Deployment',
       'metadata': {'annotations': {'deployment.kubernetes.io/revision': '5',
         ...

  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 189, in __call_api
    raise e
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 182, in __call_api
    response_data = await self.request(
                          │    └ <function ApiClient.request at 0x7f0659d5fca0>
                          └ <kubernetes_asyncio.client.api_client.ApiClient object at 0x7f06597f8880>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 230, in POST
    return (await self.request("POST", url,
                  │    │               └ 'https://192.168.39.78:8443/apis/extensions/v1beta1/namespaces/default/deployments/web-main/rollback'
                  │    └ <function RESTClientObject.request at 0x7f0659d5f1f0>
                  └ <kubernetes_asyncio.client.rest.RESTClientObject object at 0x7f065763a280>
  File "/home/linkous/.cache/pypoetry/virtualenvs/servox-eNeZ9xha-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 187, in request
    raise ApiException(http_resp=r)
          │                      └ <kubernetes_asyncio.client.rest.RESTResponse object at 0x7f065763a0a0>
          └ <class 'kubernetes_asyncio.client.exceptions.ApiException'>

kubernetes_asyncio.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 11 Nov 2020 19:16:24 GMT', 'Content-Length': '174')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

**Comment by linkous8** [comment]
Here's and expanded version of the log (including manual validation that the pod became ready. I ran these in a seperate shell while the servo poetry shell was running) [pod_updated_log.txt](https://github.com/opsani/servox/files/5532078/pod_updated_log.txt)

**Comment by linkous8** [comment]
@blakewatters I was doing some testing today against a clean main branch and came across this issue again. Here are the steps to reproduce:

* Run `minikube start`
* `kubectl apply -f` the following manifest: (not directly related, but the `command` is set to make the container never ready when adjusted to 128Mi; I'm using it to test status rejected logic I am working on)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-main
  labels:
    app: web
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      role: main
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        role: main
    spec:
      containers:
        - name: main
          image: opsani/co-http:latest
          command:
          - bash
          - -c
          - "if [ $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) -gt 191058816 ]; then /usr/local/bin/http; else sleep 1d; fi"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            failureThreshold: 1000000
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

```
* Set your servo.yaml to the following:
```yaml
kubernetes:
  deployments:
  - name: web-main
    namespace: default
    containers: 
    - name: main
      cpu:
        max: '1'
        min: 125m
        step: 125m
      memory:
        max: 1.0GiB
        min: 128.0MiB
        step: 128.0MiB
    replicas:
      max: 2
      min: 0
      pinned: True
    timeout: 5m
  description: co-http web rollout
```
* Run `servo adjust web-main/main.mem=512Mi`
